### ISSUE TITLE
S3 Denied when deploying CFN.

### ISSUE THREAD

**Issue by mitechniq** [doitintl/AWSlack#7]
I tried to deploy the CFN but I get the following error:

`GetObject for awslack/source/code.zip. S3 Error Code: AllAccessDisabled. S3 Error Message: All access to this object has been disabled`

**Comment by jeremykoerber** [comment]
I'm getting the same issue. This project looks perfect, please assist.
`Your access has been denied by S3, please make sure your request credentials have permission to GetObject for awslack/source/code.zip. S3 Error Code: AllAccessDisabled. S3 Error Message: All access to this object has been disabled`
Thank you

**Comment by jeremykoerber** [comment]
@mitechniq If you're still interested, I have a working fork here: https://github.com/jeremykoerber/AWSlack
It looks like they move the Cloudformation template and `code.zip` to another bucket, but the template wasn't updated. My fork is using my S3 buckets, so the Cloudformation link in the Readme works. But you can feel free to host the template and zipfile yourself.  All necessary files are in the repo.

**Comment by Dror88** [comment]
@jeremykoerber yep. It seems that the account with that bucket was closed. 
I uploaded it to a new bucket and updated the template/link for convenience, but feel free to use it from your own buckets...
